# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_qt_mainwindow.ui'
#
# Created: Thu Feb 12 11:08:57 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(820, 614)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txt_address = QtGui.QLineEdit(self.centralwidget)
        self.txt_address.setObjectName("txt_address")
        self.gridLayout_3.addWidget(self.txt_address, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.txt_username = QtGui.QLineEdit(self.centralwidget)
        self.txt_username.setObjectName("txt_username")
        self.gridLayout_3.addWidget(self.txt_username, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.txt_password = QtGui.QLineEdit(self.centralwidget)
        self.txt_password.setEchoMode(QtGui.QLineEdit.Password)
        self.txt_password.setObjectName("txt_password")
        self.gridLayout_3.addWidget(self.txt_password, 1, 2, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 1, 1, 1)
        self.cbo_operation = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo_operation.sizePolicy().hasHeightForWidth())
        self.cbo_operation.setSizePolicy(sizePolicy)
        self.cbo_operation.setObjectName("cbo_operation")
        self.cbo_operation.addItem("")
        self.cbo_operation.addItem("")
        self.cbo_operation.addItem("")
        self.gridLayout_4.addWidget(self.cbo_operation, 1, 0, 1, 1)
        self.cbo_class_or_instance = QtGui.QComboBox(self.centralwidget)
        self.cbo_class_or_instance.setEditable(True)
        self.cbo_class_or_instance.setObjectName("cbo_class_or_instance")
        self.cbo_class_or_instance.addItem("")
        self.gridLayout_4.addWidget(self.cbo_class_or_instance, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_execute = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_execute.sizePolicy().hasHeightForWidth())
        self.btn_execute.setSizePolicy(sizePolicy)
        self.btn_execute.setDefault(True)
        self.btn_execute.setObjectName("btn_execute")
        self.horizontalLayout_4.addWidget(self.btn_execute)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tree_results = QtGui.QTreeWidget(self.centralwidget)
        self.tree_results.setUniformRowHeights(True)
        self.tree_results.setObjectName("tree_results")
        self.gridLayout_2.addWidget(self.tree_results, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.btn_collapse = QtGui.QPushButton(self.centralwidget)
        self.btn_collapse.setObjectName("btn_collapse")
        self.horizontalLayout_2.addWidget(self.btn_collapse)
        self.btn_expand = QtGui.QPushButton(self.centralwidget)
        self.btn_expand.setObjectName("btn_expand")
        self.horizontalLayout_2.addWidget(self.btn_expand)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cbo_operation.setCurrentIndex(0)
        self.cbo_class_or_instance.setCurrentIndex(0)
        QtCore.QObject.connect(self.btn_expand, QtCore.SIGNAL("clicked()"), self.tree_results.expandAll)
        QtCore.QObject.connect(self.btn_collapse, QtCore.SIGNAL("clicked()"), self.tree_results.collapseAll)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "WBEM GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Address / URI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Operation / Method", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Class or Instance Name", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_operation.setItemText(0, QtGui.QApplication.translate("MainWindow", "EnumerateInstances", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_operation.setItemText(1, QtGui.QApplication.translate("MainWindow", "EnumerateInstanceNames", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_operation.setItemText(2, QtGui.QApplication.translate("MainWindow", "GetInstance", None, QtGui.QApplication.UnicodeUTF8))
        self.cbo_class_or_instance.setItemText(0, QtGui.QApplication.translate("MainWindow", "CIM_ComputerSystem", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_execute.setText(QtGui.QApplication.translate("MainWindow", "            Execute            ", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_results.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.tree_results.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Results (double-click an instance name to copy it to the clipboard)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_collapse.setText(QtGui.QApplication.translate("MainWindow", "Collapse All", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_expand.setText(QtGui.QApplication.translate("MainWindow", "Expand All", None, QtGui.QApplication.UnicodeUTF8))

